[phases.setup]
nixPkgs = ["php82",
  "php82Packages.composer",
  "php82Extensions.gd",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
[start]
cmd = "php -d extension=gd.so artisan serve --host=0.0.0.0 --port=$PORT"